import { describe, expect, it } from "vitest";
import { createCircle } from "../circle/create-circle.ts";
import { generateInvite } from "../circle/generate-invite.ts";
import { joinCircle } from "../circle/join-circle.ts";
import { leaveCircle } from "../circle/leave-circle.ts";
import { addCommitment } from "../commitment/add-commitment.ts";
import { createSeason } from "../season/create-season.ts";
import { editSeasonParams } from "../season/edit-season-params.ts";
import type { CircleId, SeasonId } from "../shared/ids.ts";
import { habitId, seasonId, userId } from "../shared/ids.ts";
import type { TestApp } from "../testing/app-harness.ts";
import { createTestApp } from "../testing/app-harness.ts";
import { createFixedOffsetTimeZone } from "../testing/fixed-time-zone.ts";
import { instant } from "../time/instant.ts";
import { approvePact } from "./approve-pact.ts";

function actorFor(id: string) {
  return { userId: userId(id) };
}

const NOW = instant(1_759_060_800_000); // 2025-09-28T12:00:00.000Z (noon, stable local date)

const DONE_MEASURE = {
  unit: "done" as const,
  frequency: { kind: "timesPerWeek" as const, times: 3 },
};

/** Adds `actorId` as a member via an invite generated by the circle's creator (user-andrea). */
async function joinCircleAs(app: TestApp, circleId: CircleId, actorId: string) {
  const invite = await generateInvite(app, actorFor("user-andrea"), { circleId });
  if (!invite.ok) throw new Error("fixture setup failed");
  const joined = await joinCircle(app, actorFor(actorId), { inviteCode: invite.value.code });
  if (!joined.ok) throw new Error("fixture setup failed");
  return joined.value;
}

async function addFullWeightCommitment(app: TestApp, seasonIdValue: SeasonId, actorId: string) {
  const result = await addCommitment(app, actorFor(actorId), {
    seasonId: seasonIdValue,
    habitId: habitId(`habit-${actorId}`),
    weightPercent: 100,
    privacy: "visible",
    measure: DONE_MEASURE,
  });
  if (!result.ok) throw new Error("fixture setup failed");
  return result.value;
}

/** GIVEN: a circle + open-pact season with `count` members, each with a single 100%-weight commitment. */
async function seasonWithFullyWeightedMembers(
  app: TestApp,
  count: number,
  startDate = "2025-10-01",
  timezone = "UTC",
) {
  const circle = await createCircle(app, actorFor("user-andrea"), { name: "Río Runners" });
  if (!circle.ok) throw new Error("fixture setup failed");
  const otherActorIds = Array.from({ length: count - 1 }, (_, i) => `user-member-${i}`);
  for (const actorId of otherActorIds) {
    await joinCircleAs(app, circle.value.id, actorId);
  }
  const season = await createSeason(app, actorFor("user-andrea"), {
    circleId: circle.value.id,
    timezone,
    startDate,
    lengthWeeks: 8,
  });
  if (!season.ok) throw new Error("fixture setup failed");

  let current = season.value;
  current = await addFullWeightCommitment(app, current.id, "user-andrea");
  for (const actorId of otherActorIds) {
    current = await addFullWeightCommitment(app, current.id, actorId);
  }
  return {
    circle: circle.value,
    season: current,
    memberActorIds: ["user-andrea", ...otherActorIds],
  };
}

function utcTestApp(now = NOW) {
  return createTestApp({ now, timeZone: createFixedOffsetTimeZone({ offsetMinutes: 0 }) });
}

describe("approvePact", () => {
  it("PA-1: the last approval closes the pact and the season becomes active", async () => {
    const app = utcTestApp();
    const { season, memberActorIds } = await seasonWithFullyWeightedMembers(app, 3);

    const first = await approvePact(app, actorFor(memberActorIds[0] as string), {
      seasonId: season.id,
      expectedPactRevision: season.pactRevision,
    });
    const second = await approvePact(app, actorFor(memberActorIds[1] as string), {
      seasonId: season.id,
      expectedPactRevision: season.pactRevision,
    });
    expect(first.ok).toBe(true);
    expect(second.ok).toBe(true);
    if (!first.ok || !second.ok) return;
    expect(second.value.status).toBe("pactOpen");

    const third = await approvePact(app, actorFor(memberActorIds[2] as string), {
      seasonId: season.id,
      expectedPactRevision: season.pactRevision,
    });

    expect(third.ok).toBe(true);
    if (!third.ok) return;
    expect(third.value.status).toBe("active");
    expect(third.value.pactClosedAt).not.toBeNull();
    expect(third.value.approvals).toHaveLength(3);
  });

  it("PI-2: approving, and the approval that closes the pact, leave pactRevision unchanged", async () => {
    const app = utcTestApp();
    const { season, memberActorIds } = await seasonWithFullyWeightedMembers(app, 2);

    const first = await approvePact(app, actorFor(memberActorIds[0] as string), {
      seasonId: season.id,
      expectedPactRevision: season.pactRevision,
    });
    const closing = await approvePact(app, actorFor(memberActorIds[1] as string), {
      seasonId: season.id,
      expectedPactRevision: season.pactRevision,
    });

    expect(first.ok && closing.ok).toBe(true);
    if (!first.ok || !closing.ok) return;
    expect(first.value.pactRevision).toBe(season.pactRevision);
    expect(closing.value.status).toBe("active");
    expect(closing.value.pactRevision).toBe(season.pactRevision);
  });

  it("new PA-11 (B4): a solo circle's single member closes their own pact", async () => {
    const app = utcTestApp();
    const { season, memberActorIds } = await seasonWithFullyWeightedMembers(app, 1);

    const result = await approvePact(app, actorFor(memberActorIds[0] as string), {
      seasonId: season.id,
      expectedPactRevision: season.pactRevision,
    });

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.value.status).toBe("active");
    expect(result.value.approvals).toHaveLength(1);
  });

  it("PA-9: a non-member cannot approve", async () => {
    const app = utcTestApp();
    const { season } = await seasonWithFullyWeightedMembers(app, 1);

    const result = await approvePact(app, actorFor("user-outsider"), {
      seasonId: season.id,
      expectedPactRevision: season.pactRevision,
    });

    expect(result).toEqual({ ok: false, error: { kind: "NotAMember" } });
  });

  it("rejects when the season does not exist", async () => {
    const app = utcTestApp();

    const result = await approvePact(app, actorFor("user-andrea"), {
      seasonId: seasonId("season-ghost"),
      expectedPactRevision: 0,
    });

    expect(result).toEqual({ ok: false, error: { kind: "SeasonNotFound" } });
  });

  it("rejects once the pact is already closed", async () => {
    const app = utcTestApp();
    const { season } = await seasonWithFullyWeightedMembers(app, 1);
    const closed = await approvePact(app, actorFor("user-andrea"), {
      seasonId: season.id,
      expectedPactRevision: season.pactRevision,
    });
    if (!closed.ok) throw new Error("fixture setup failed");
    expect(closed.value.status).toBe("active");

    const result = await approvePact(app, actorFor("user-andrea"), {
      seasonId: season.id,
      expectedPactRevision: season.pactRevision,
    });

    expect(result).toEqual({ ok: false, error: { kind: "PactNotOpen" } });
  });

  it("new PA-10 (B5): rejects when the approving member's own weights don't sum to 100%", async () => {
    const app = utcTestApp();
    const circle = await createCircle(app, actorFor("user-andrea"), { name: "Río Runners" });
    if (!circle.ok) throw new Error("fixture setup failed");
    const season = await createSeason(app, actorFor("user-andrea"), {
      circleId: circle.value.id,
      timezone: "UTC",
      startDate: "2025-10-01",
      lengthWeeks: 8,
    });
    if (!season.ok) throw new Error("fixture setup failed");
    const withCommitment = await addCommitment(app, actorFor("user-andrea"), {
      seasonId: season.value.id,
      habitId: habitId("habit-run"),
      weightPercent: 60,
      privacy: "visible",
      measure: DONE_MEASURE,
    });
    if (!withCommitment.ok) throw new Error("fixture setup failed");

    const result = await approvePact(app, actorFor("user-andrea"), {
      seasonId: withCommitment.value.id,
      expectedPactRevision: withCommitment.value.pactRevision,
    });

    expect(result).toEqual({ ok: false, error: { kind: "CommitmentWeightsNotFull" } });
  });

  it("B5: a member with zero commitments cannot approve", async () => {
    const app = utcTestApp();
    const circle = await createCircle(app, actorFor("user-andrea"), { name: "Río Runners" });
    if (!circle.ok) throw new Error("fixture setup failed");
    const season = await createSeason(app, actorFor("user-andrea"), {
      circleId: circle.value.id,
      timezone: "UTC",
      startDate: "2025-10-01",
      lengthWeeks: 8,
    });
    if (!season.ok) throw new Error("fixture setup failed");

    const result = await approvePact(app, actorFor("user-andrea"), {
      seasonId: season.value.id,
      expectedPactRevision: season.value.pactRevision,
    });

    expect(result).toEqual({ ok: false, error: { kind: "CommitmentWeightsNotFull" } });
  });

  it("PA-7-corrected/B3: closing on the nominal start date starts the season that day", async () => {
    const app = utcTestApp(instant(1_759_305_600_000) /* 2025-10-01T08:00Z */);
    const { season, memberActorIds } = await seasonWithFullyWeightedMembers(app, 1);
    expect(season.nominalStart).toBe("2025-10-01");

    const result = await approvePact(app, actorFor(memberActorIds[0] as string), {
      seasonId: season.id,
      expectedPactRevision: season.pactRevision,
    });

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.value.actualStart).toBe("2025-10-01");
    expect(result.value.lengthWeeks).toBe(8);
  });

  it("PA-7-corrected/B3: closing after the nominal start date shifts actualStart to the next day, full length kept", async () => {
    const creationApp = utcTestApp(instant(1_759_046_400_000) /* 2025-09-28T08:00Z */);
    const { season, memberActorIds } = await seasonWithFullyWeightedMembers(creationApp, 1);
    expect(season.nominalStart).toBe("2025-10-01");
    // Re-use the same in-memory stores under a clock 3 days after the nominal start.
    const lateApp: TestApp = {
      ...creationApp,
      clock: { now: () => instant(1_759_564_800_000) /* 2025-10-04T08:00Z */ },
    };

    const result = await approvePact(lateApp, actorFor(memberActorIds[0] as string), {
      seasonId: season.id,
      expectedPactRevision: season.pactRevision,
    });

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    expect(result.value.actualStart).toBe("2025-10-05");
    expect(result.value.lengthWeeks).toBe(8);
  });

  it("re-approving is idempotent: it does not duplicate the member's approval entry", async () => {
    const app = utcTestApp();
    const { season, memberActorIds } = await seasonWithFullyWeightedMembers(app, 2);

    const first = await approvePact(app, actorFor(memberActorIds[0] as string), {
      seasonId: season.id,
      expectedPactRevision: season.pactRevision,
    });
    if (!first.ok) throw new Error("fixture setup failed");
    const second = await approvePact(app, actorFor(memberActorIds[0] as string), {
      seasonId: first.value.id,
      expectedPactRevision: first.value.pactRevision,
    });

    expect(second.ok).toBe(true);
    if (!second.ok) return;
    expect(second.value.approvals).toHaveLength(1);
    expect(second.value.status).toBe("pactOpen");
  });

  it("unanimity is judged over ACTIVE members: after one leaves, the remaining members' approvals close the pact", async () => {
    const app = utcTestApp();
    const { circle, season, memberActorIds } = await seasonWithFullyWeightedMembers(app, 3);
    const [andrea, member0, leaver] = memberActorIds as [string, string, string];
    const left = await leaveCircle(app, actorFor(leaver), { circleId: circle.id });
    if (!left.ok) throw new Error("fixture setup failed");
    // Leaving changes the pact (approvals reset), so callers must re-read its revision.
    const reread = await app.seasons.get(season.id);
    if (!reread) throw new Error("fixture setup failed");

    const first = await approvePact(app, actorFor(andrea), {
      seasonId: season.id,
      expectedPactRevision: reread.pactRevision,
    });
    const second = await approvePact(app, actorFor(member0), {
      seasonId: season.id,
      expectedPactRevision: reread.pactRevision,
    });

    expect(first.ok && first.value.status).toBe("pactOpen");
    expect(second.ok && second.value.status).toBe("active");
  });

  it("the closing date is resolved in the season's own timezone, not UTC (B3)", async () => {
    // Created on 2025-09-28; closing instant is 2025-10-02T01:00Z = 2025-10-01 22:00 in Santiago (UTC-3).
    const creationApp = createTestApp({ now: instant(1_759_046_400_000) });
    const { season, memberActorIds } = await seasonWithFullyWeightedMembers(
      creationApp,
      1,
      "2025-10-01",
      "America/Santiago",
    );
    const lateApp: TestApp = {
      ...creationApp,
      clock: { now: () => instant(1_759_366_800_000) },
    };

    const result = await approvePact(lateApp, actorFor(memberActorIds[0] as string), {
      seasonId: season.id,
      expectedPactRevision: season.pactRevision,
    });

    expect(result.ok).toBe(true);
    if (!result.ok) return;
    // Local date is still the nominal start (10-01), so no shift. In UTC it would be 10-02 -> 10-03.
    expect(result.value.actualStart).toBe("2025-10-01");
  });

  describe("expectedPactRevision precondition (PI-S1..S4)", () => {
    const stale = { ok: false, error: { kind: "StaleSeason" } };

    it("PI-S1: rejects StaleSeason when the pact changed since the caller read it, and writes nothing", async () => {
      const app = utcTestApp();
      const { season, memberActorIds } = await seasonWithFullyWeightedMembers(app, 2);
      const edited = await editSeasonParams(app, actorFor("user-andrea"), {
        seasonId: season.id,
        lengthWeeks: 6,
      });
      if (!edited.ok) throw new Error("fixture setup failed");
      expect(edited.value.pactRevision).toBe(season.pactRevision + 1);
      const before = await app.seasons.get(season.id);

      const result = await approvePact(app, actorFor(memberActorIds[0] as string), {
        seasonId: season.id,
        expectedPactRevision: season.pactRevision,
      });

      expect(result).toEqual(stale);
      expect(await app.seasons.get(season.id)).toEqual(before);
    });

    it("PI-S2: PactNotOpen beats StaleSeason", async () => {
      const app = utcTestApp();
      const { season } = await seasonWithFullyWeightedMembers(app, 1);
      const closed = await approvePact(app, actorFor("user-andrea"), {
        seasonId: season.id,
        expectedPactRevision: season.pactRevision,
      });
      if (!closed.ok) throw new Error("fixture setup failed");

      const result = await approvePact(app, actorFor("user-andrea"), {
        seasonId: season.id,
        expectedPactRevision: season.pactRevision + 7,
      });

      expect(result).toEqual({ ok: false, error: { kind: "PactNotOpen" } });
    });

    it("PI-S3: StaleSeason beats CommitmentWeightsNotFull", async () => {
      const app = utcTestApp();
      const circle = await createCircle(app, actorFor("user-andrea"), { name: "Río Runners" });
      if (!circle.ok) throw new Error("fixture setup failed");
      const season = await createSeason(app, actorFor("user-andrea"), {
        circleId: circle.value.id,
        timezone: "UTC",
        startDate: "2025-10-01",
        lengthWeeks: 8,
      });
      if (!season.ok) throw new Error("fixture setup failed");

      const result = await approvePact(app, actorFor("user-andrea"), {
        seasonId: season.value.id,
        expectedPactRevision: season.value.pactRevision + 1,
      });

      expect(result).toEqual(stale);
    });

    it("PI-S4: approving with the current revision succeeds and leaves the revision unchanged", async () => {
      const app = utcTestApp();
      const { season, memberActorIds } = await seasonWithFullyWeightedMembers(app, 2);

      const result = await approvePact(app, actorFor(memberActorIds[0] as string), {
        seasonId: season.id,
        expectedPactRevision: season.pactRevision,
      });

      expect(result.ok && result.value.pactRevision).toBe(season.pactRevision);
    });
  });
});
